import streamlit as st
import pandas as pd
from datetime import date, timedelta
from fpdf import FPDF
from database.db_handler import fetch_iocs, fetch_stats
from config import APP_TITLE, APP_VERSION


def render():
    st.markdown(
        "<h1 style='text-align: center;'>📄 Report Generator</h1>",
        unsafe_allow_html=True
    )
    st.markdown(
        "<p style='text-align: center; color: gray;'>"
        "Export a threat intelligence report for a selected time range"
        "</p>",
        unsafe_allow_html=True
    )
    st.markdown(
        "<p style='text-align: center; font-size: 12px; color: #555;'>"
        "Made by Luis Duarte"
        "</p>",
        unsafe_allow_html=True
    )
    st.divider()

    col1, col2 = st.columns(2)
    with col1:
        date_from = st.date_input("From", value=date.today() - timedelta(days=7))
    with col2:
        date_to = st.date_input("To", value=date.today())

    severity_filter = st.multiselect(
        "Include severities",
        ["Critical", "High", "Medium", "Low"],
        default=["Critical", "High"]
    )

    report_format = st.radio("Export format", ["CSV", "PDF"], horizontal=True)

    if st.button("📥 Generate Report", use_container_width=True):
        with st.spinner("Building report..."):
            df = fetch_iocs(
                date_from=str(date_from),
                date_to=str(date_to),
                limit=5000,
            )

            if severity_filter:
                df = df[df["severity"].isin(severity_filter)]

            if df.empty:
                st.warning("No IoCs found for the selected filters.")
                return

            if report_format == "CSV":
                csv = df.to_csv(index=False).encode("utf-8")
                st.download_button(
                    label=f"⬇️ Download CSV ({len(df)} IoCs)",
                    data=csv,
                    file_name=f"threatscope_report_{date_from}_{date_to}.csv",
                    mime="text/csv",
                )

            else:  # PDF
                pdf_bytes = _generate_pdf(df, date_from, date_to)
                st.download_button(
                    label=f"⬇️ Download PDF ({len(df)} IoCs)",
                    data=pdf_bytes,
                    file_name=f"threatscope_report_{date_from}_{date_to}.pdf",
                    mime="application/pdf",
                )

        st.success(f"Report ready — {len(df)} IoCs included.")
        st.dataframe(df.head(20), use_container_width=True)
        if len(df) > 20:
            st.caption(f"Showing first 20 of {len(df)} rows. Full data in downloaded file.")


def _generate_pdf(df: pd.DataFrame,
                  date_from: date, date_to: date) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, APP_TITLE, ln=True, align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, "Threat Intelligence Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, f"Period: {date_from} to {date_to}", ln=True, align="C")
    pdf.cell(0, 6, f"Generated by {APP_TITLE} v{APP_VERSION} — Made by Luis Duarte", ln=True, align="C")
    pdf.ln(6)

    # Summary
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)

    sev_counts = df["severity"].value_counts().to_dict()
    pdf.cell(0, 6, f"Total IoCs in period: {len(df)}", ln=True)
    for sev in ["Critical", "High", "Medium", "Low"]:
        pdf.cell(0, 6, f"  {sev}: {sev_counts.get(sev, 0)}", ln=True)
    pdf.ln(4)

    src_counts = df["source"].value_counts().to_dict()
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "IoCs by Source", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for src, cnt in src_counts.items():
        pdf.cell(0, 6, f"  {src}: {cnt}", ln=True)
    pdf.ln(4)

    # IoC table (first 200)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "IoC List (first 200)", ln=True)
    pdf.set_font("Helvetica", "B", 8)

    headers = ["Value", "Type", "Source", "Severity", "Score", "Country"]
    widths  = [65, 25, 25, 20, 15, 20]

    for h, w in zip(headers, widths):
        pdf.cell(w, 7, h, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    for _, row in df.head(200).iterrows():
        value   = str(row.get("value", ""))[:35]
        itype   = str(row.get("ioc_type", ""))[:12]
        source  = str(row.get("source", ""))[:10]
        sev     = str(row.get("severity", ""))
        score   = f"{row.get('score', 0):.1f}"
        country = str(row.get("country", "") or "")[:8]

        for val, w in zip([value, itype, source, sev, score, country], widths):
            pdf.cell(w, 6, val, border=1)
        pdf.ln()

    return bytes(pdf.output())